stages:
  data_cleaning:
    cmd: python src/data_cleaning.py
    deps:
      - data/raw/Music Info.csv
      - src/data_cleaning.py
    outs: 
      - data/cleaned_data.csv

  transform_data:
    cmd: python src/content_based_filtering.py
    deps:
      - data/cleaned_data.csv
      - src/content_based_filtering.py
      - src/data_cleaning.py
    outs:
      - data/transformed_data.npz
      - transformer.joblib